//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "climb")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub climb_id: i64,
    pub date_logged: String,
    pub checks: i64,
    pub grade_adj: String,
    pub grade: String,
    pub number: Option<String>,
    pub color: String,
    pub color_secondary: Option<String>,
    pub wall_name: String,
    pub name: Option<String>,
    pub setter_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
